# Parameters that describe server
n_server_rounds: 15 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 8 # The number of clients in the FL experiment
local_epochs: 5 # The number of epochs to complete for client
batch_size: 10 # The batch size for client training
