# Parameters that describe server
n_server_rounds: 50 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 3 # The number of clients in the FL experiment
local_steps: 10 # The number of local steps (one per batch) to complete for client
batch_size: 128 # The batch size for client training
