# Parameters that describe server
n_server_rounds: 3 # The number of rounds to run FL

# Parameters that describe clients
n_clients: 2 # The number of clients in the FL experiment
local_steps: 100 # The number of epochs to complete for client
batch_size: 8 # The batch size for client training
num_classes: 4 # number of classes in the classification task.

# checkpointing
checkpoint_path: "examples/bert_finetuning_example"

sample_percentage: 0.75 # the proportion of the training data that will actually be used in training
beta: 1.0 # controls the heterogeneity of the data distributions among clients
